name: Run upload_legislation_national.py daily

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 오전 10:00 (KST) → UTC 기준 01:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account key file
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > service_account.json

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
        run: python upload_legislation_national.py
